# -*- coding: utf-8 -*-
"""getting_HTML_from_a_webpage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NmvCWcLjDU1de2crkCeOTYz8QTJOTmHV
"""

from bs4 import BeautifulSoup
import requests

url = "https://www.scrapethissite.com/"

page = requests.get(url)

soup = BeautifulSoup(page.text, "html.parser")

print(soup.prettify())

